### ISSUE TITLE
 No such file or directory:matrix_win_10total_count.npy

### ISSUE THREAD

**Issue by xycim** [7fantasysz/MSCRED#13]
when run py file  ,get error:
Traceback (most recent call last):
  File "matrix_generator.py", line 185, in <module>
    generate_train_test_data()
  File "matrix_generator.py", line 149, in generate_train_test_data
    data_all.append(np.load(path_temp))
  File "D:\anaconda3\lib\site-packages\numpy\lib\npyio.py", line 428, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'd:/ts_data_csv2/signature_matrix/matrix_win_10total_count.npy'

how to get this file?

**Comment by henuliulei** [comment]
same question

**Comment by hhxmn** [comment]
怎么解决啊，我也遇到了

**Comment by cui502** [comment]
解决了吗，我也是这个问题，缺乏一些数据。
